{% set name = "textual-serve" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/textual_serve-{{ version }}.tar.gz
  sha256: 9332716464a1fca38bb5421ef29e38bdc5d304e5a15faa3ae1f8dcb185a7885c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 

requirements:
  host:
    - python >=3.8,<4
    - pip
    - hatchling
  run:
    - python >=3.8,<4
    - aiohttp >=3.9.5
    - aiohttp-jinja2 >=1.6
    - jinja2 >=3.1.4
    - rich
    - textual >=0.66.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - textual_serve

about:
  home: https://github.com/Textualize/textual-serve
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Serve Textual apps locally
  dev_url: https://github.com/Textualize/textual-serve

extra:
  recipe-maintainers:
    - davidbrochart
